# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'design.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(777, 673)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit.setGeometry(QtCore.QRect(10, 10, 541, 41))
        self.lineEdit.setObjectName("lineEdit")
        self.textBrowser = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser.setGeometry(QtCore.QRect(10, 60, 211, 341))
        self.textBrowser.setObjectName("textBrowser")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(560, 10, 75, 41))
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(640, 10, 71, 41))
        self.pushButton_2.setObjectName("pushButton_2")
        self.map_scheme = QtWidgets.QRadioButton(self.centralwidget)
        self.map_scheme.setGeometry(QtCore.QRect(20, 420, 82, 17))
        self.map_scheme.setObjectName("map_scheme")
        self.map_sputnik = QtWidgets.QRadioButton(self.centralwidget)
        self.map_sputnik.setGeometry(QtCore.QRect(20, 450, 82, 17))
        self.map_sputnik.setObjectName("map_sputnik")
        self.map_hybrid = QtWidgets.QRadioButton(self.centralwidget)
        self.map_hybrid.setGeometry(QtCore.QRect(20, 480, 82, 17))
        self.map_hybrid.setObjectName("map_hybrid")
        self.map_up = QtWidgets.QPushButton(self.centralwidget)
        self.map_up.setGeometry(QtCore.QRect(640, 500, 41, 31))
        self.map_up.setObjectName("map_up")
        self.map_down = QtWidgets.QPushButton(self.centralwidget)
        self.map_down.setGeometry(QtCore.QRect(640, 560, 41, 31))
        self.map_down.setObjectName("map_down")
        self.map_left = QtWidgets.QPushButton(self.centralwidget)
        self.map_left.setGeometry(QtCore.QRect(600, 530, 41, 31))
        self.map_left.setObjectName("map_left")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(270, 100, 481, 391))
        self.label_2.setObjectName("label_2")
        self.horizontalSlider = QtWidgets.QSlider(self.centralwidget)
        self.horizontalSlider.setGeometry(QtCore.QRect(200, 530, 351, 22))
        self.horizontalSlider.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider.setObjectName("horizontalSlider")
        self.map_right = QtWidgets.QPushButton(self.centralwidget)
        self.map_right.setGeometry(QtCore.QRect(680, 530, 41, 31))
        self.map_right.setObjectName("map_right")
        self.coord_true = QtWidgets.QCheckBox(self.centralwidget)
        self.coord_true.setGeometry(QtCore.QRect(10, 540, 131, 17))
        self.coord_true.setObjectName("coord_true")
        self.mail_true = QtWidgets.QCheckBox(self.centralwidget)
        self.mail_true.setGeometry(QtCore.QRect(10, 570, 191, 17))
        self.mail_true.setObjectName("mail_true")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 777, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButton.setText(_translate("MainWindow", "Поиск"))
        self.pushButton_2.setText(_translate("MainWindow", "Сброс"))
        self.map_scheme.setText(_translate("MainWindow", "Схема"))
        self.map_sputnik.setText(_translate("MainWindow", "Спутник"))
        self.map_hybrid.setText(_translate("MainWindow", "Гибрид"))
        self.map_up.setText(_translate("MainWindow", "Вверх"))
        self.map_down.setText(_translate("MainWindow", "Вниз"))
        self.map_left.setText(_translate("MainWindow", "Лево"))
        self.label_2.setText(_translate("MainWindow", "Ваша карта)"))
        self.map_right.setText(_translate("MainWindow", "Право"))
        self.coord_true.setText(_translate("MainWindow", "Отображать коорды?"))
        self.mail_true.setText(_translate("MainWindow", "Отображать почтовый адрес?"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
